# Generated by Django 3.2.3 on 2022-10-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstats',
            name='linux',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
